# Generated by Django 4.1.2 on 2022-11-10 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_alter_meals_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meals',
            old_name='preparationtime',
            new_name='preperation_time',
        ),
    ]
