# Generated by Django 4.1.4 on 2023-01-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_rename_preparationtime_meals_preperation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
    ]
